#!/usr/bin/env bash
#
# Install specified packages.
#

set -x
set -e

if which dpkg &> /dev/null; then
  apt-get update
  apt-get -y install "$@"
elif which rpm &> /dev/null; then
  yum install -y "$@"
else
  echo "No package manager found."
fi